---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: udp-server
  name: udp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udp-server
    spec:
      containers:
      - image: geerd/udp_server:0.1
        imagePullPolicy: IfNotPresent
        name: udp-server
        ports:
        - name: server
          protocol: UDP
          containerPort: 21000
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: PORT
            value: "21000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udp-server
  name: udp-server
spec:
  ports:
  - name: serer
    port: 21000
    protocol: UDP
    targetPort: 21000
  selector:
    app: udp-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udp-server
  name: udp-server-nodeports
spec:
  ports:
  - name: server
    protocol: UDP
    port: 21000
  selector:
    app: udp-server
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: udp-server-nodeports-21000
spec:
  backend:
    serviceName: udp-server-nodeports
    servicePort: 21000
